server:
  port: 9090

spring:
  # \u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    # \u6570\u636E\u5E93\u9A71\u52A8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # \u8FDE\u63A5\u6570\u636E\u5E93\u7684url
    url: jdbc:mysql://localhost:3306/analysis_sys_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    # \u7528\u6237\u540D
    username: root
    # \u5BC6\u7801
    password: 123456
    # \u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u7684\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      pool-name: DateHikariCP
      # \u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      minimum-idle: 5
      # \u7A7A\u95F2\u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4\uFF0C\u9ED8\u8BA4600000\uFF0810\u5206\u949F\uFF09
      idle-timeout: 180000
      # \u6700\u5927\u8FDE\u63A5\u6570\uFF0C\u9ED8\u8BA410
      maximum-pool-size: 15
      # \u4ECE\u8FDE\u63A5\u6C60\u8FD4\u56DE\u7684\u8FDE\u63A5\u81EA\u52A8\u63D0\u4EA4
      auto-commit: true
      # \u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4\uFF0C1800000\uFF0830\u5206\u949F\uFF09
      max-lifetime: 1800000
      # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF0C\u9ED8\u8BA430000\uFF0830\u79D2\uFF09
      connection-timeout: 30000
      # \u6D4B\u8BD5\u8FDE\u63A5\u662F\u5426\u53EF\u7528\u7684\u67E5\u8BE2\u8BED\u53E5
#      connection-test-query: SELECT * FROM user

  # redis\u914D\u7F6E
  redis:
    # \u670D\u52A1\u5668\u5730\u5740
    host: 127.0.0.1
    # \u7AEF\u53E3
    port: 6379
    # redis\u5BC6\u7801
    password:
    # \u6570\u636E\u5E93\uFF0C\u9ED8\u8BA4\u662F0
    database: 0
    # \u8D85\u65F6\u65F6\u95F4
    timeout: 1209600000ms
    lettuce:
      pool:
        # \u6700\u5927\u8FDE\u63A5\u6570\uFF0C\u9ED8\u8BA4\u662F8
        max-active: 10
        # \u6700\u5927\u8FDE\u63A5\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF0C\u9ED8\u8BA4\u662F-1
        max-wait: 10000ms
        # \u6700\u5927\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u9ED8\u8BA4\u662F8
        max-idle: 100
        # \u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u9ED8\u8BA4\u662F0
        min-idle: 5

  jackson:
    # \u65F6\u533A\u8BBE\u7F6E
    time-zone: GMT+8

  # servlet\u7684\u8BBE\u7F6E
  servlet:
    multipart:
      # \u4E0A\u4F20\u6587\u4EF6\u7684\u6700\u5927\u5927\u5C0F
      max-file-size: 100MB

  # \u90AE\u4EF6\u670D\u52A1\u914D\u7F6E
  mail:
    # \u90AE\u4EF6\u670D\u52A1\u5668\u5730\u5740
    host: 123.126.97.113
    # \u7528\u6237\u540D
    username: hzx1966752024@163.com
    # POP3/IMAP/SMTP\u670D\u52A1\u6388\u6743\u7801
    password: JCLECTJHLVEACWXQ
    # \u6635\u79F0
    nickname: hzx

    properties:
      mail:
        # \u662F\u5426\u5F00\u542F DEBUG \u6A21\u5F0F\uFF0C\u8FD9\u6837\uFF0C\u90AE\u4EF6\u53D1\u9001\u8FC7\u7A0B\u7684\u65E5\u5FD7\u4F1A\u5728\u63A7\u5236\u53F0\u6253\u5370\u51FA\u6765\uFF0C\u65B9\u4FBF\u6392\u67E5\u9519\u8BEF
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            # \u914D\u7F6ESSL \u52A0\u5BC6\u5DE5\u5382
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    # \u7AEF\u53E3 465\u6216994
    port: 465
    # \u9ED8\u8BA4\u7684\u90AE\u4EF6\u7F16\u7801\u4E3AUTF-8
    default-encoding: UTF-8



# mybatis-plus\u914D\u7F6E
mybatis-plus:
  configuration:
    # \u5F00\u542FSQL\u65E5\u5FD7
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # \u5173\u95EDSQL\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # \u4E0D\u5F00\u542F\u9A7C\u5CF0\u8F6C\u6362
    map-underscore-to-camel-case: false

# \u81EA\u5B9A\u4E49\u914D\u7F6E
file:
  ip: localhost

# oss\u914D\u7F6E
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucket-name: hzx-oss
    access-key-id: LTAI5tQcjbvbjA5JjMMkUkc1
    access-key-secret: GpUJboqMqecakDNBSVlUPhnaKfjGfY


# Swagger2\u914D\u7F6E
my:
  swagger:
    enabled: true
    docked:
      title: \u63A5\u53E3\u6587\u6863
      description: \u5728\u7EBF\u63A5\u53E3\u6587\u6863
      version: 0.1
      basePackage: com.example.demo.controller

scrap_host: 426qb33844.goho.co
remote_host1: 47.115.211.201:5000
remote_host2: 426qb33844.goho.co
